### ISSUE TITLE
Nothing happens when clicking continue button

### ISSUE THREAD

**Issue by jonbhanson** [mhrst/sign_in_with_apple_js#10]
Hello, thanks for this package!

I have set up the plugin in my app using Flutter web, and I open the signin dialog in an external window.  The sign in flow seems to work fine, but when the screen asks _"Do you want to continue using MyApp with your Apple ID “user@email.com”?"_ and I click _"Continue"_, the screen does not change.  I opened Chrome DevTools, and I see an authorize message sent with an authorization response that looks successful:

```json
{
    "authorization": {
        "id_token": "eyJraWQiOiJlWG...",
        "grant_code": "cf4e065...",
        "scope": [
            "name",
            "email"
        ]
    },
    "authorizedData": {
        "userId": "001605..."
    },
    "consentRequired": false,
    "enableSignInWithAppleNewFirstTimeRunScreen": false,
    "reAuthorization": false
}
```

However, I expect the window to close or redirect, and the Flutter code `await signInWithApple();` to return a value, but none of that happens.  Am I missing something?

**Comment by mhrst** [comment]
Not sure why you're getting stuck there -- I haven't experienced an issue like this in the browser.

I've seen similar behavior on the iOS v14.4 Simulator with Apple Sign In. The solution there is to use a downgraded version of iOS in the Simulator -- I can't see how this might be related.

You should see `await signInWithApple()` resolve with an [SignInResponseI](https://pub.dev/documentation/sign_in_with_apple_js/latest/apple_id/SignInResponseI-class.html) object after clicking the 'Continue' button, but it sounds like that is never closing the popup.


Are you using `usePopup: true/false` in the client configuration?

**Comment by jonbhanson** [comment]
I am using usePopup: true in the client config, so the sign in opens in a new window.

**Comment by jonbhanson** [comment]
It seems I am missing something here.  How does the redirectURI fit with this package?  [Apple docs](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/configuring_your_webpage_for_sign_in_with_apple) state that _"Apple processes the authorization request, and sends an HTTP POST request containing the results of the authorization to the URL provided in redirectURI."_  But how is this information supposed to make it back to the `sign_in_with_apple_js` package?

**Comment by jonbhanson** [comment]
I tried using `usePopup: false` and it triggered the following exception:

```
TypeError: Cannot read property 'then' of undefined
    at Object.promiseToFuture (http://localhost:50080/dart_sdk.js:57644:15)
    at Object.signInWithApple (http://localhost:50080/packages/sign_in_with_apple_js/_web_only.dart.lib.js:44:20)
    at Object.signInWithApple (http://localhost:50080/packages/sign_in_with_apple_js/sign_in_with_apple_js.dart.lib.js:39:22)
    at signMeInWithApple (http://localhost:50080/packages/Xchangr/utils.dart.lib.js:69:55)
    at signMeInWithApple.next (<anonymous>)
    at runBody (http://localhost:50080/dart_sdk.js:37228:34)
    at Object._async [as async] (http://localhost:50080/dart_sdk.js:37259:7)
    at Function.signMeInWithApple (http://localhost:50080/packages/Xchangr/utils.dart.lib.js:65:20)
    at http://localhost:50080/packages/Xchangr/home/login_screen.dart.lib.js:157:47
    at Generator.next (<anonymous>)
    at runBody (http://localhost:50080/dart_sdk.js:37228:34)
    at Object._async [as async] (http://localhost:50080/dart_sdk.js:37259:7)
    at flutter_login.LoginProvider.new.<anonymous> (http://localhost:50080/packages/Xchangr/home/login_screen.dart.lib.js:156:167)
    at http://localhost:50080/packages/flutter_login/src/widgets/auth_card.dart.lib.js:5662:501
    at auth_card._LoginCardState.new._loginProviderSubmit (http://localhost:50080/packages/flutter_login/src/widgets/auth_card.dart.lib.js:5578:24)
    at _loginProviderSubmit.next (<anonymous>)
    at http://localhost:50080/dart_sdk.js:37209:33
    at _RootZone.runUnary (http://localhost:50080/dart_sdk.js:37080:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:50080/dart_sdk.js:32336:29)
    at handleValueCallback (http://localhost:50080/dart_sdk.js:32863:49)
    at Function._propagateToListeners (http://localhost:50080/dart_sdk.js:32901:17)
    at _Future.new.[_completeWithValue] (http://localhost:50080/dart_sdk.js:32749:23)
    at http://localhost:50080/dart_sdk.js:32690:39
    at _RootZone.runUnary (http://localhost:50080/dart_sdk.js:37080:59)
    at _FutureListener.then.handleValue (http://localhost:50080/dart_sdk.js:32336:29)
    at handleValueCallback (http://localhost:50080/dart_sdk.js:32863:49)
    at Function._propagateToListeners (http://localhost:50080/dart_sdk.js:32901:17)
    at _Future.new.[_completeWithValue] (http://localhost:50080/dart_sdk.js:32749:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50080/dart_sdk.js:32770:35)
    at Object._microtaskLoop (http://localhost:50080/dart_sdk.js:37332:13)
    at _startMicrotaskLoop (http://localhost:50080/dart_sdk.js:37338:13)
    at http://localhost:50080/dart_sdk.js:33109:9
```

**Comment by jonbhanson** [comment]
Note that the exception above was when I first opened the sign in with apple, before I even entered my login info.

**Comment by jonbhanson** [comment]
The strange thing is, when I step through the code line-by-line with _step into_, it does not trigger the above exception.  I tried it a couple times both ways (running and stepping) and it triggers the exception when running but not when stepping.  I don't know if that gives any clues.  I'm trying to figure this out, but I haven't used dart with JS, so it's a learning curve for me.

**Comment by mhrst** [comment]
> It seems I am missing something here. How does the redirectURI fit with this package? Apple docs state that "Apple processes the authorization request, and sends an HTTP POST request containing the results of the authorization to the URL provided in redirectURI." But how is this information supposed to make it back to the sign_in_with_apple_js package?

The Apple docs are a little confusing. While redirectURI is always required, it's only POSTed to when `usePopup: false`. 
- With `usePopup: false`, your browser will navigate to the Apple Sign In page. Then Apple's sign-in page will POST to the redirectURI. 
- With `usePopup: true`, the redirectURI is never used.

> I tried using usePopup: false and it triggered the following exception:

This exception from `usePopup: false` is an issue. It should be returning `null` because the browser will be navigating away from the Flutter app with this option. Are you still being navigated to the Apple Sign In page?

>The strange thing is, when I step through the code line-by-line with step into, it does not trigger the above exception. I tried it a couple times both ways (running and stepping) and it triggers the exception when running but not when stepping. I don't know if that gives any clues. I'm trying to figure this out, but I haven't used dart with JS, so it's a learning curve for me.

The web debugging is a little spotty, especially with asynchronous code. It may be that the redirect is blocked by the breakpoint in some way.

**Comment by jonbhanson** [comment]
> This exception from `usePopup: false` is an issue.

OK, so I should probably wait for you to update the package before further testing, then?

> Are you still being navigated to the Apple Sign In page?

Yes, it triggers the exception, but the navigation to the Apple Sign In still occurs.

**Comment by mhrst** [comment]
> > This exception from `usePopup: false` is an issue.
> 
> OK, so I should probably wait for you to update the package before further testing, then?

`usePopup: false` will still work despite the exception. I pushed an update to the master branch (4bbc8ab14953d39445b0a8c491c5e3e68f439d9b) that resolves this exception.

I've also filled out the demo app (ebbde21834275be93a4a2828f6bb2688e646f2ec) that can be run with `webdev serve` out of the `example` directory. However, you'll need to provide your own client-id and redirect-uri in `web/example.dart`.

> > Are you still being navigated to the Apple Sign In page?
> 
> Yes, it triggers the exception, but the navigation to the Apple Sign In still occurs.

Signing in will cause a POST to the redirect-uri. Because handling that POST response requires a server-side component, it's generally easier to `usePopup: true`.

**Comment by mhrst** [comment]
Here's something else to check:

In working on an example and looking into #12, I found that this happens when using Apple Sign In on a misconfigured domain.

Make sure your domain is listed under the Domains & Subdomains configured in the apple service id:
<img width="649" alt="Screen Shot 2021-04-16 at 3 26 01 PM" src="https://user-images.githubusercontent.com/1178412/115089842-0fc2bb00-9ec8-11eb-8670-19e62ccd7c04.png">

**Comment by m-j-g** [comment]
I'm having the same issue, "Nothing happens when clicking continue button".  loading indicator displays for a second then stops and theres no message or anything.  I checked my domains & subdomains, made sure it was there.  And am using usePopup: true.  going to keep digging into it to see what I can learn.

**Comment by jonbhanson** [comment]
I have verified that the subdomains are configured in the service id, as well as the return URL.  I am also testing from the production domain, not localhost.  When I hit the continue button of the apple login, the apple server is replying with 200 code POST that has a JSON payload that looks like this:

```json
{
  "authorization" : {
    "id_token" : "eyJraWS2dgTVC4v8...",
    "grant_code" : "c23b285a...",
    "scope" : [ "name", "email" ]
  },
  "authorizedData" : {
    "userId" : "001605..."
  },
  "consentRequired" : false,
  "enableSignInWithAppleNewFirstTimeRunScreen" : false,
  "reAuthorization" : false
}
```

It seems like everything is configured correctly, but nothing happens... I'm still stumped.

**Comment by jonbhanson** [comment]
I was able to resolve by switching to Firebase Auth's build-in sign in mechanism:

```dart
await FirebaseAuth.instance.signInWithRedirect(OAuthProvider('apple.com'));
```
