### ISSUE TITLE
Can't get past 'continue' to get response.

### ISSUE THREAD

**Issue by fremfi** [mhrst/sign_in_with_apple_js#12]
Here are the errors I get please help;

<img width="1032" alt="Screen Shot 2021-04-16 at 3 10 12 PM" src="https://user-images.githubusercontent.com/20648834/115072926-e2750d80-9ec5-11eb-8270-2b6eae4729f7.png">

**Comment by fremfi** [comment]
I found a differen't solution. closing this.

**Comment by mhrst** [comment]
Just to note: This happens when the domain you are using for your app does not match a domain configured in the Service ID in your Apple Developer account.

Most commonly this happens when running on **localhost**. Apple Sign In JS does not support running from **localhost**.

**Comment by jonbhanson** [comment]
@fremfi if I can ask, what was your different solution?

**Comment by fremfi** [comment]
> @fremfi if I can ask, what was your different solution?

I use firebase, so I used this library: https://pub.dev/packages/firebase_auth_oauth
