### ISSUE TITLE
Rename library to apple_id_auth

### ISSUE THREAD

**Issue by mhrst** [mhrst/sign_in_with_apple_js#5]
Matching the javascript API, the library is named as:

```dart
library AppleID.auth
```

-- a violation of static analysis rule: `INFO: Name libraries using ``lowercase_with_underscores``.`

**Comment by hhtokpinar** [comment]
it seems there's a problem after renaming it. It throws an exception in the console when I pressed the button like **ReferenceError AppleID is not defined**
but strangely it works only on local
